spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret = ${JWT_SECRET:SenhaSuperSecretaSegura123!}
api.security.token.expirationMinutes = 30